// this is just my idea !! you don't need to take it or anything :)
// this project is cool by the way
function activityGenerator() {
    const activities = [
        "Go outside and take pictures!",
        "Go look for geocaches!",
        "Count how many trees you see outside!",
        "Listen to new music genres!",
        "Learn a new language!",
        "Look for flowers!",
        "Learn a coding language!",
        "Read a book!",
        "Look for some spare change!",
        "Go swimming!",
        "Go take a nap!",
        "Watch TV!",
        "Talk to new people!",
        "Play with a friend!",
        "Tell scary ghost stories!",
        "Play chess!",
        "Take a break!",
        "Talk to someone!",
        "Make something!",
        "Draw something you like!",
        "Give a gift to someone!",
        "Donate money to charity!",
        "Cook a meal for someone!",
        "Make a sticker!",
        "Do origami!",
        "Buy a Raspberry Pi!",
        "Sell old stuff!",
        "Count your money!",
        "Feed some ducks!",
        "Build a robot!",
        "Drink water!",
        "Play some games!",
        "Look for a cat!",
        "Look for a dog!",
        "Do some homework!",
        "Have some fun!",
        "Join a organization!",
        "Start a club!",
        "Make a map!",
        "Make a project with code!",
        "Spend time with others!",
        "Bake cookies!",
        "Look for treasure!",
        "Make a time capsule!",
        "Make a sticky note wall!",
        "Sing a song!",
        "Mail something to someone!",
        "Go outside and take a walk!",
        "Make a video!",
        "Spread some love around!",
        "Crack some jokes!",
        "Create a new language!",
        "Create a new operating system!",
        "Find a solution to any problem!",
        "Make a wish!",
        "Code with friends!",
        "Work on a project with someone!",
        "Pet an animal!",
        "Find a zebra!",
        "Look for a Giraffe",
        "Eat some pie!",
        "Eat some cake!",
        "Find some gold!",
        "Code until you can't!",
        "Make music!",
        "Create something funny!",
        "Find a pool noodle!",
        "Look for a mop and clean!",
        "Make a box fort!",
        "Look for discounted stuff!",
        "Debug some code!",
        "Mess around with AI!",
        "Make ASCII Art!",
        "Build a robot!",
        "Give away old stuff!",
        "Take pictures!",
        "Pick up trash outside!",
        "Go to the animal shelter and take care of one!",
        "Learn morse code!",
        "Learn binary!",
        "Learn about routers!",
        "Learn Rust!",
        "Create a pumpkin!",
        "Check your emails!",
        "Send a nice letter to someone!",
        "Help someone!",
        "Do a personality test!",
        "Chase a butterfly!",
        "Give someone a hug!",
        "Check out Advent of Code!",
        "Get a degree in something!",
        "Make some funny clips!",
        "Look at social media!",
        "Learn about bash!",
        "Learn command prompt!",
        "Learn about Linux!",
        "Learn about NixOs!",
        "Learn more about Windows!",
        "Learn more about pc parts!",
        "Learn more about Cybersecurity!"
    ];

    // Get a random activity from the array
    const randomIndex = Math.floor(Math.random() * activities.length);
    const activity = activities[randomIndex];

    // Update the DOM
    document.getElementById("activity-output").innerHTML = activity;
}
